TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# In a Diamond Support Module, install
# templates like this
#
DB += zebraLastDivDiff.template            
DB += zebraRegisterWritePosCompInp.template
DB += zebraRegisterWrite32.template        
DB += zebraRegisterWritePrescaler.template
DB += zebraRegisterWriteBitfield.template  
DB += zebraRegisterWrite.template
DB += zebraRegisterWriteMux.template       
DB += zebra.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE


